"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class stark(object):
    __slots__ = ["number1", "number2"]

    def __init__(self):
        self.number1 = 0
        self.number2 = 0

    def encode(self):
        buf = BytesIO()
        buf.write(stark._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.number1, self.number2))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != stark._get_packed_fingerprint():
            raise ValueError("Decode error")
        return stark._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = stark()
        self.number1, self.number2 = struct.unpack(">qq", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if stark in parents: return 0
        tmphash = (0xd9695655e6e5255d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if stark._packed_fingerprint is None:
            stark._packed_fingerprint = struct.pack(">Q", stark._get_hash_recursive([]))
        return stark._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

